baseURL = 'https://zhidongzhang.cn/'
languageCode = 'zh-cn'
title = 'Zhidong Zhang'
theme = []

[markup]
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['$$', '$$'], ['\\[', '\\]']]
      inline = [['$', '$'], ['\\(', '\\)']]

  [markup.highlight]
    style = "friendly"
    noClasses = true
    guessSyntax = true

[permalinks]
  blogs = "/blogs/:title/"

[params]
  name = "Zhang Zhidong"
  role = "M.Sc Student in Computational Neuroscience"
  organization = "University of Tübingen"
  location = "Tübingen, Germany"
  description = "I am interested in Artificial Intelligence, Machine Learning, and Computer Vision."
  avatar = "images/真人头像.jpg" 

  # Sidebar links
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/ZhidongZhang96"
  [[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/zhidong-zhang-136a94311/"
  [[params.social]]
    name = "Twitter"
    icon = "x-twitter"
    url = "https://x.com/ZhangZhidong"
  [[params.social]]
    name = "Google Scholar"
    icon = "google-scholar"
    pack = "ai"
    url = "https://scholar.google.com/citations?user=weFOAukAAAAJ"
  [[params.social]]
    name = "Email"
    icon = "envelope"
    pack = "fas"
    url = "mailto:zhidong.zhang96@foxmail.com"

[menu]
  [[menu.main]]
    identifier = "highlights"
    name = "Highlights"
    url = "/#highlights"
    weight = 1
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/#publications"
    weight = 3
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/#projects"
    weight = 4
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 5

